/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package client.gui;

//import hethongnhathuocduocankhang.bus.TraHangBUS;
//import hethongnhathuocduocankhang.dao.ChiTietHoaDonDAO;
//import hethongnhathuocduocankhang.dao.ChiTietPhieuTraDAO;
//import hethongnhathuocduocankhang.dao.ChiTietXuatLoDAO;
//import hethongnhathuocduocankhang.dao.HoaDonDAO;
//import hethongnhathuocduocankhang.dao.KhachHangDAO;
//import hethongnhathuocduocankhang.dao.LoSanPhamDAO;
//import hethongnhathuocduocankhang.dao.NhanVienDAO;
//import hethongnhathuocduocankhang.dao.PhieuDatHangDAO;
//import hethongnhathuocduocankhang.dao.PhieuTraHangDAO;
//import hethongnhathuocduocankhang.entity.ChiTietHoaDon;
//import hethongnhathuocduocankhang.entity.ChiTietPhieuTraHang;
//import hethongnhathuocduocankhang.entity.HoaDon;
//import hethongnhathuocduocankhang.entity.NhanVien;
//import hethongnhathuocduocankhang.entity.PhieuTraHang;
//import hethongnhathuocduocankhang.entity.TinhTrangSanPhamEnum;
//import hethongnhathuocduocankhang.entity.TruongHopDoiTraEnum;
import client.socket.SocketClient;
import common.dto.ChiTietHoaDonDTO;
import common.dto.ChiTietPhieuTraHangDTO;
import common.dto.HoaDonDTO;
import common.dto.KhachHangDTO;
import common.dto.PhieuTraHangDTO;
import common.network.CommandType;
import common.network.Request;
import common.network.Response;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.AbstractButton;
import javax.swing.ActionMap;
import javax.swing.BorderFactory;
import javax.swing.DefaultCellEditor;
import javax.swing.InputMap;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.ScrollPaneConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author trand
 */
public class TraHangGUI extends javax.swing.JPanel {

    private JLabel lblSoLanTra;
    private JLabel lblSoNgayHD;
    private JLabel lblTongTienTra;
//    private final TraHangBUS traHangBUS = new TraHangBUS();
    /**
     * Creates new form TraHangGUI
     */
    public TraHangGUI() {
        initComponents();
        initInfoPanels(); // Khởi tạo 3 ô thông tin

        mapKeyToFocus("F3", txtNhapMaHoaDon);
        mapKeyToClickButton("F7", btnChonTatCa);
        mapKeyToClickButton("F8", btnBoChonTatCa);
        mapKeyToClickButton("F4", btnXacNhan);

        mapKeyToClickButton("F9", btnXoaDong);
        mapKeyToClickButton("F10", btnXoaRong);
        mapKeyToClickButton("F6", btnTaoPhieu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel24 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        txtNhapMaHoaDon = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jPanel30 = new javax.swing.JPanel();
        btnChonTatCa = new javax.swing.JButton();
        btnBoChonTatCa = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCTHD = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel3 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtTenKhachHang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        txtDiemTichLuy = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDiemTru = new javax.swing.JTextField();
        jPanel28 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTongThanhTien = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        btnXoaDong = new javax.swing.JButton();
        btnXoaRong = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnTaoPhieu = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaPhieuTraHang = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtMaHoaDonTrongPhieuTraHang = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTraHang = new javax.swing.JTable();

        setLayout(new java.awt.GridLayout(1, 0));

        jPanel8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel8KeyPressed(evt);
            }
        });
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));

        jPanel13.setLayout(new java.awt.GridLayout(1, 2));
        jPanel13.add(jPanel26);

        jPanel9.add(jPanel13);

        jPanel11.setLayout(new java.awt.GridLayout(1, 2));

        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        jPanel25.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel25.add(jPanel27);

        txtNhapMaHoaDon.setDocument(new javax.swing.text.PlainDocument() {
            @Override
            public void insertString(int offs, String str, javax.swing.text.AttributeSet a) throws javax.swing.text.BadLocationException {
                if (str == null) return;
                String upperStr = str.toUpperCase(); // Luôn in hoa

                // 1. Giả lập: Nếu cho phép nhập thì chuỗi mới sẽ trông như thế nào?
                StringBuilder sb = new StringBuilder(getText(0, getLength()));
                sb.insert(offs, upperStr);
                String futureString = sb.toString();

                // 2. Xử lý độ dài: Nếu vượt quá 14 ký tự
                if (futureString.length() > 20) {
                    // Nếu người dùng đang PASTE (chuỗi nhập vào dài > 1) -> Tự động cắt bớt cho vừa
                    if (upperStr.length() > 1) {
                        int spaceLeft = 14 - getLength();
                        if (spaceLeft > 0) {
                            upperStr = upperStr.substring(0, spaceLeft);
                            // Tính lại chuỗi giả lập sau khi cắt
                            sb = new StringBuilder(getText(0, getLength()));
                            sb.insert(offs, upperStr);
                            futureString = sb.toString();
                        } else return; // Hết chỗ chứa -> Chặn
                    } else {
                        return; // Nếu đang GÕ phím mà vượt quá -> Chặn luôn
                    }
                }

                // 3. Kiểm tra logic bắt buộc đầu phải là "HD"
                // Regex "^H?D?.*" nghĩa là:
                // - Ký tự 1 bắt buộc là H (hoặc rỗng)
                // - Ký tự 2 bắt buộc là D (hoặc rỗng)
                // VD: Gõ "A" -> Chặn. Gõ "H" -> OK. Gõ tiếp "A" (thành HA) -> Chặn. Gõ "D" (thành HD) -> OK.
                // Paste "HD-123" -> OK. Paste "AB-123" -> Chặn.
                if (!futureString.matches("^H?D?.*")) {
                    return;
                }

                super.insertString(offs, upperStr, a);
            }
        });
        txtNhapMaHoaDon.setText("[F3]");
        txtNhapMaHoaDon.setPreferredSize(new java.awt.Dimension(400, 30));
        txtNhapMaHoaDon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNhapMaHoaDonFocusGained(evt);
            }
        });
        txtNhapMaHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNhapMaHoaDonActionPerformed(evt);
            }
        });
        txtNhapMaHoaDon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNhapMaHoaDonKeyPressed(evt);
            }
        });
        jPanel25.add(txtNhapMaHoaDon);

        btnTimKiem.setBackground(new java.awt.Color(25, 118, 210));
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel25.add(btnTimKiem);

        jPanel14.add(jPanel25);

        jPanel11.add(jPanel14);

        jPanel30.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnChonTatCa.setText("Chọn tất cả [F7]");
        btnChonTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonTatCaActionPerformed(evt);
            }
        });
        jPanel30.add(btnChonTatCa);

        btnBoChonTatCa.setText("Bỏ chọn tất cả [F8]");
        btnBoChonTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoChonTatCaActionPerformed(evt);
            }
        });
        jPanel30.add(btnBoChonTatCa);

        jPanel23.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        jPanel23.add(jPanel12);

        jLabel6.setText("Số lượng đã chọn: 0");
        jPanel23.add(jLabel6);

        jPanel30.add(jPanel23);

        btnXacNhan.setBackground(new java.awt.Color(0, 203, 0));
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("Xác nhận [F4]");
        btnXacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXacNhanMouseClicked(evt);
            }
        });
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        jPanel30.add(btnXacNhan);
        jPanel30.add(jPanel16);

        jPanel11.add(jPanel30);

        jPanel9.add(jPanel11);

        jPanel8.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết hóa đơn"));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));

        jScrollPane2.setBorder(null);

        tblCTHD.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "STT", "Mã CTHD", "Tên sản phẩm", "Số lượng", "Đơn vị tính", "Đơn giá", "Giảm giá", "Thành tiền", "Chọn"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCTHD.setShowGrid(false);
        tblCTHD.setShowHorizontalLines(true);
        tblCTHD.setShowVerticalLines(true);
        jScrollPane2.setViewportView(tblCTHD);
        if (tblCTHD.getColumnModel().getColumnCount() > 0) {
            tblCTHD.getColumnModel().getColumn(0).setMinWidth(50);
            tblCTHD.getColumnModel().getColumn(0).setMaxWidth(50);
            tblCTHD.getColumnModel().getColumn(1).setMinWidth(0);
            tblCTHD.getColumnModel().getColumn(1).setMaxWidth(0);
            tblCTHD.getColumnModel().getColumn(2).setMinWidth(300);
            tblCTHD.getColumnModel().getColumn(2).setMaxWidth(300);
            tblCTHD.getColumnModel().getColumn(8).setResizable(false);
        }

        jPanel10.add(jScrollPane2);
        jScrollPane2.getAccessibleContext().setAccessibleName("");

        jPanel8.add(jPanel10, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);
        jPanel8.add(jToolBar1, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Tìm hóa đơn", jPanel8);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel20.setMinimumSize(new java.awt.Dimension(474, 33));
        jPanel20.setLayout(new javax.swing.BoxLayout(jPanel20, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel8.setText("Khách hàng");
        jPanel1.add(jLabel8);

        txtTenKhachHang.setEditable(false);
        txtTenKhachHang.setEnabled(false);
        txtTenKhachHang.setPreferredSize(new java.awt.Dimension(150, 25));
        txtTenKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKhachHangActionPerformed(evt);
            }
        });
        jPanel1.add(txtTenKhachHang);

        jLabel7.setText("Điểm tích lũy");
        jPanel1.add(jLabel7);

        jPanel31.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        txtDiemTichLuy.setEditable(false);
        txtDiemTichLuy.setEnabled(false);
        txtDiemTichLuy.setPreferredSize(new java.awt.Dimension(100, 25));
        txtDiemTichLuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemTichLuyActionPerformed(evt);
            }
        });
        jPanel31.add(txtDiemTichLuy);

        jLabel9.setText("Trừ điểm tích lũy");
        jPanel31.add(jLabel9);

        txtDiemTru.setEditable(false);
        txtDiemTru.setEnabled(false);
        txtDiemTru.setPreferredSize(new java.awt.Dimension(100, 25));
        txtDiemTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemTruActionPerformed(evt);
            }
        });
        jPanel31.add(txtDiemTru);
        jPanel31.add(jPanel28);

        jLabel5.setText("Tổng tiền hoàn trả");
        jPanel31.add(jLabel5);

        txtTongThanhTien.setEditable(false);
        txtTongThanhTien.setPreferredSize(new java.awt.Dimension(160, 25));
        jPanel31.add(txtTongThanhTien);

        jPanel1.add(jPanel31);
        jPanel1.add(jPanel22);

        btnXoaDong.setBackground(new java.awt.Color(255, 51, 51));
        btnXoaDong.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaDong.setText("Xóa dòng [F9]");
        btnXoaDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDongActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoaDong);

        btnXoaRong.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaRong.setForeground(new java.awt.Color(0, 0, 0));
        btnXoaRong.setText("Xóa rỗng [F10]");
        btnXoaRong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaRongActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoaRong);
        jPanel1.add(jPanel2);

        btnTaoPhieu.setBackground(new java.awt.Color(0, 203, 0));
        btnTaoPhieu.setForeground(new java.awt.Color(255, 255, 255));
        btnTaoPhieu.setText("Tạo phiếu [F6]");
        btnTaoPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoPhieuActionPerformed(evt);
            }
        });
        jPanel1.add(btnTaoPhieu);
        jPanel1.add(jPanel17);

        jPanel20.add(jPanel1);

        jPanel3.add(jPanel20, java.awt.BorderLayout.PAGE_END);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setText("Mã phiếu trả hàng");
        jLabel1.setPreferredSize(new java.awt.Dimension(110, 16));
        jPanel7.add(jLabel1);

        txtMaPhieuTraHang.setEditable(false);
        txtMaPhieuTraHang.setMinimumSize(new java.awt.Dimension(64, 25));
        txtMaPhieuTraHang.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel7.add(txtMaPhieuTraHang);

        jPanel6.add(jPanel7);

        jLabel2.setText("Nhân viên");
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel15.add(jLabel2);

        jTextField3.setEditable(false);
        jTextField3.setPreferredSize(new java.awt.Dimension(250, 25));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel15.add(jTextField3);

        jPanel6.add(jPanel15);

        jLabel3.setText("Ngày lập phiếu");
        jLabel3.setPreferredSize(new java.awt.Dimension(110, 16));
        jPanel18.add(jLabel3);

        jTextField5.setEditable(false);
        jTextField5.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel18.add(jTextField5);

        jPanel6.add(jPanel18);

        jLabel4.setText("Mã hóa đơn");
        jLabel4.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel19.add(jLabel4);

        txtMaHoaDonTrongPhieuTraHang.setEditable(false);
        txtMaHoaDonTrongPhieuTraHang.setPreferredSize(new java.awt.Dimension(250, 25));
        txtMaHoaDonTrongPhieuTraHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHoaDonTrongPhieuTraHangActionPerformed(evt);
            }
        });
        jPanel19.add(txtMaHoaDonTrongPhieuTraHang);

        jPanel6.add(jPanel19);

        jPanel4.add(jPanel6);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết phiếu trả hàng"));
        jPanel21.setLayout(new javax.swing.BoxLayout(jPanel21, javax.swing.BoxLayout.Y_AXIS));

        tblTraHang.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "STT", "Tên sản phẩm", "Số lượng", "Đơn giá", "Giảm giá", "Thành tiền", "Lý do trả", "Sản phẩm nguyên vẹn", "Giá trị hoàn trả", "Thành tiền hoàn trả", "Mã CTHD"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, true, false, false, false, true, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTraHang.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblTraHangPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblTraHang);
        if (tblTraHang.getColumnModel().getColumnCount() > 0) {
            tblTraHang.getColumnModel().getColumn(0).setMinWidth(50);
            tblTraHang.getColumnModel().getColumn(0).setMaxWidth(50);
            tblTraHang.getColumnModel().getColumn(1).setMinWidth(200);
            tblTraHang.getColumnModel().getColumn(1).setMaxWidth(200);
            tblTraHang.getColumnModel().getColumn(6).setMinWidth(200);
            tblTraHang.getColumnModel().getColumn(7).setMinWidth(100);
            tblTraHang.getColumnModel().getColumn(10).setMinWidth(0);
            tblTraHang.getColumnModel().getColumn(10).setMaxWidth(0);
        }

        jPanel21.add(jScrollPane1);

        jPanel5.add(jPanel21);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Phiếu trả hàng", jPanel3);

        add(jTabbedPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNhapMaHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNhapMaHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNhapMaHoaDonActionPerformed

    private void txtDiemTichLuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemTichLuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemTichLuyActionPerformed

    private void txtTenKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKhachHangActionPerformed

    private void txtDiemTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemTruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemTruActionPerformed

    private void btnXoaDongActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXoaDongActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblTraHang.getModel();
        dtm.removeRow(tblTraHang.getSelectedRow());
    }// GEN-LAST:event_btnXoaDongActionPerformed

    private void txtMaHoaDonTrongPhieuTraHangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtMaHoaDonTrongPhieuTraHangActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtMaHoaDonTrongPhieuTraHangActionPerformed

    private void jXDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jXDatePicker1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jXDatePicker1ActionPerformed

    private void txtNhapMaHoaDonFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtNhapMaHoaDonFocusGained
        // TODO add your handling code here:
        txtNhapMaHoaDon.setText("");
    }// GEN-LAST:event_txtNhapMaHoaDonFocusGained

    private void txtNhapMaHoaDonKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtNhapMaHoaDonKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            timHoaDonDeTraHang();
        }
    }// GEN-LAST:event_txtNhapMaHoaDonKeyPressed

    private void btnXacNhanMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnXacNhanMouseClicked
        // TODO add your handling code here:

    }// GEN-LAST:event_btnXacNhanMouseClicked

    private void btnXoaRongActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXoaRongActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblTraHang.getModel();
        dtm.setRowCount(0);
        txtTongThanhTien.setText("");
    }// GEN-LAST:event_btnXoaRongActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXacNhanActionPerformed
        // Lấy tên nhân viên hiện tại từ server
        Request reqNV = new Request(CommandType.GET_NHAN_VIEN_BY_MA,
                GiaoDienChinhGUI.getTk().getMaNV());
        Response resNV = SocketClient.getInstance().sendRequest(reqNV);
        if (resNV.isSuccess() && resNV.getData() != null) {
            jTextField3.setText(resNV.getData().toString());
        }

        DefaultTableModel dtmCTHD = (DefaultTableModel) tblCTHD.getModel();
        int soLuongChon = 0;
        for (int i = 0; i < dtmCTHD.getRowCount(); i++) {
            if (dtmCTHD.getValueAt(i, 8) == Boolean.TRUE
                    && Integer.parseInt(dtmCTHD.getValueAt(i, 3).toString()) > 0) {
                soLuongChon++;
            }
        }
        jLabel6.setText("Số lượng đã chọn: " + soLuongChon);

        DefaultTableModel dtmTraHang = (DefaultTableModel) tblTraHang.getModel();
        dtmTraHang.setRowCount(0);

        int count = 0;
        int sttTra = 1;
        for (int i = 0; i < dtmCTHD.getRowCount(); i++) {
            if (dtmCTHD.getValueAt(i, 8) == Boolean.TRUE
                    && Integer.parseInt(dtmCTHD.getValueAt(i, 3).toString()) > 0) {

                // Đọc thẳng từ tblCTHD – không cần gọi server lại
                // tblCTHD: STT | Mã CTHD | Tên SP | SL | ĐVT | Đơn giá | Giảm giá | Thành tiền | Chọn
                String maCTHD    = dtmCTHD.getValueAt(i, 1).toString();
                String tenSP     = dtmCTHD.getValueAt(i, 2).toString();
                int    soLuong   = Integer.parseInt(dtmCTHD.getValueAt(i, 3).toString());
                Object donGia    = dtmCTHD.getValueAt(i, 5);
                Object giamGia   = dtmCTHD.getValueAt(i, 6);
                Object thanhTien = dtmCTHD.getValueAt(i, 7);

                // Build row cho tblTraHang
                // tblTraHang: STT | Tên SP | SL | Đơn giá | Giảm giá | Thành tiền |
                //             Lý do | Nguyên vẹn | % hoàn | Tiền hoàn | Mã CTHD
                Object[] rowData = new Object[]{
                        sttTra++,
                        tenSP,
                        soLuong,
                        donGia,
                        giamGia,
                        thanhTien,
                        "Hàng lỗi do nhà sản xuất",   // lý do mặc định
                        Boolean.TRUE,                  // SP nguyên vẹn mặc định
                        "100%",                        // % hoàn trả mặc định
                        thanhTien,                     // tiền hoàn ban đầu = thành tiền
                        maCTHD
                };
                dtmTraHang.addRow(rowData);
                taoLyDo();
                count++;
            }
        }

        capNhatTongThanhTien();
        if (count > 0) {
            jTabbedPane1.setSelectedIndex(1);
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn sản phẩm muốn trả");
        }
    }// GEN-LAST:event_btnXacNhanActionPerformed

    private void btnBoChonTatCaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBoChonTatCaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtmTraHang = (DefaultTableModel) tblTraHang.getModel();
        dtmTraHang.setRowCount(0);

        DefaultTableModel dtmCTHD = (DefaultTableModel) tblCTHD.getModel();
        for (int i = 0; i < dtmCTHD.getRowCount(); i++) {
            if (dtmCTHD.getValueAt(i, 8) == Boolean.TRUE) {
                dtmCTHD.setValueAt(Boolean.FALSE, i, 8);
            }
        }
    }// GEN-LAST:event_btnBoChonTatCaActionPerformed

    private void btnTaoPhieuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTaoPhieuActionPerformed
        int chon = JOptionPane.showConfirmDialog(null, "Xác nhận tạo phiếu trả?",
                "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (chon != JOptionPane.YES_OPTION) return;

        DefaultTableModel dtm = (DefaultTableModel) tblTraHang.getModel();
        if (dtm.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Chưa có sản phẩm nào trong phiếu trả!");
            return;
        }

        // ── 1. Tạo phiếu trả hàng (header) — server tự sinh mã ──
        PhieuTraHangDTO headerDTO = PhieuTraHangDTO.builder()
                .maNV(GiaoDienChinhGUI.getTk().getMaNV())
                .maHoaDon(txtMaHoaDonTrongPhieuTraHang.getText())
                .ngayLapPhieuTraHang(java.time.LocalDateTime.now())
                .tongTienHoaTra(boDinhDangTien(txtTongThanhTien.getText()))
                .build();

        Response resHeader = SocketClient.getInstance().sendRequest(
                new Request(CommandType.ADD_PHIEU_TRA_HANG, headerDTO));
        if (!resHeader.isSuccess()) {
            JOptionPane.showMessageDialog(null, "Lỗi khi tạo phiếu: " + resHeader.getMessage());
            return;
        }
        // Server trả về mã PTH thực tế đã lưu
        String maPTH = resHeader.getData() != null
                ? resHeader.getData().toString()
                : txtMaPhieuTraHang.getText().trim();

        // ── 2. Lưu từng chi tiết phiếu trả ─────────────────────
        for (int i = 0; i < dtm.getRowCount(); i++) {
            // tblTraHang: STT | Tên SP | SL | Đơn giá | Giảm giá | Thành tiền |
            //             Lý do | Nguyên vẹn | % hoàn | Tiền hoàn | Mã CTHD
            String  maCTHD     = dtm.getValueAt(i, 10).toString();
            int     soLuong    = ((Number) dtm.getValueAt(i, 2)).intValue();
            String  lyDo       = dtm.getValueAt(i, 6).toString();
            boolean nguyenVen  = (Boolean) dtm.getValueAt(i, 7);
            String  phanTram   = dtm.getValueAt(i, 8).toString().replace("%", "").trim();
            double  tienHoan   = boDinhDangTien(dtm.getValueAt(i, 9).toString());

            ChiTietPhieuTraHangDTO ctDTO = ChiTietPhieuTraHangDTO.builder()
                    .maPhieuTraHang(maPTH)
                    .maChiTietHoaDon(maCTHD)
                    .soLuong(soLuong)
                    .giaTriHoanTra(phanTram)   // dạng số 100, 80, 50, 30
                    .thanhTienHoanTra(tienHoan)
                    .truongHopDoiTra(mapLyDoSangEnum(lyDo))         // String enum name
                    .tinhTrangSanPham(nguyenVen ? "HANG_NGUYEN_VEN" : "HANG_KHONG_NGUYEN_VEN")
                    .build();

            Response resCT = SocketClient.getInstance().sendRequest(
                    new Request(CommandType.ADD_CHI_TIET_PHIEU_TRA_HANG, ctDTO));
            if (!resCT.isSuccess()) {
                JOptionPane.showMessageDialog(null,
                        "Lỗi khi lưu chi tiết phiếu trả: " + resCT.getMessage());
                return;
            }
        }

        jTabbedPane1.setSelectedIndex(0);
        xoaRongTatCa();
        JOptionPane.showMessageDialog(null, "Tạo phiếu trả hàng thành công!");
    }// GEN-LAST:event_btnTaoPhieuActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTimKiemActionPerformed
        timHoaDonDeTraHang();
    }// GEN-LAST:event_btnTimKiemActionPerformed

    private void btnChonTatCaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnChonTatCaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtmCTHD = (DefaultTableModel) tblCTHD.getModel();

        for (int i = 0; i < dtmCTHD.getRowCount(); i++) {
            dtmCTHD.setValueAt(Boolean.TRUE, i, 8);
        }
    }// GEN-LAST:event_btnChonTatCaActionPerformed

    private void tblTraHangPropertyChange(java.beans.PropertyChangeEvent evt) {// GEN-FIRST:event_tblTraHangPropertyChange
        DefaultTableModel dtm = (DefaultTableModel) tblTraHang.getModel();
        int selectRow = tblTraHang.getSelectedRow();
        if (selectRow < 0) return;

        boolean nguyenVen = (boolean) dtm.getValueAt(selectRow, 7);
        String lyDoStr = dtm.getValueAt(selectRow, 6).toString();
        double thanhTienGoc = boDinhDangTien(dtm.getValueAt(selectRow, 5).toString());

        // Tính % hoàn trả theo quy tắc nghiệp vụ (client-side)
        double phanTram;
        String hienThiPhanTram;
        if (nguyenVen) {
            switch (lyDoStr) {
                case "Hàng lỗi do nhà sản xuất" -> { phanTram = 1.0;  hienThiPhanTram = "100%"; }
                case "Dị ứng/mẫn cảm"          -> { phanTram = 0.5;  hienThiPhanTram = "50%";  }
                default                         -> { phanTram = 0.7;  hienThiPhanTram = "70%";  }
            }
        } else {
            switch (lyDoStr) {
                case "Hàng lỗi do nhà sản xuất" -> { phanTram = 0.8;  hienThiPhanTram = "80%";  }
                case "Dị ứng/mẫn cảm"          -> { phanTram = 0.3;  hienThiPhanTram = "30%";  }
                default                         -> { phanTram = 0.5;  hienThiPhanTram = "50%";  }
            }
        }

        double tienHoanTra = thanhTienGoc * phanTram;
        dtm.setValueAt(hienThiPhanTram, selectRow, 8);
        dtm.setValueAt(dinhDangTien(tienHoanTra), selectRow, 9);
        capNhatTongThanhTien();
    }



    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField3ActionPerformed

    private void jPanel8KeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jPanel8KeyPressed
        // TODO add your handling code here:
    }// GEN-LAST:event_jPanel8KeyPressed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoChonTatCa;
    private javax.swing.JButton btnChonTatCa;
    private javax.swing.JButton btnTaoPhieu;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnXoaDong;
    private javax.swing.JButton btnXoaRong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblCTHD;
    private javax.swing.JTable tblTraHang;
    private javax.swing.JTextField txtDiemTichLuy;
    private javax.swing.JTextField txtDiemTru;
    private javax.swing.JTextField txtMaHoaDonTrongPhieuTraHang;
    private javax.swing.JTextField txtMaPhieuTraHang;
    private javax.swing.JTextField txtNhapMaHoaDon;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JTextField txtTongThanhTien;



    // End of variables declaration//GEN-END:variables

    // Thêm hóa đơn vào "Tìm hóa đơn"
//    private void addHoaDon(String maHoaDon, HoaDon hoaDon) {
//        // hóa đơn có pth không?
//        boolean coPTH = HoaDonDAO.getSoPTH(maHoaDon) > 0;
//        System.out.println(HoaDonDAO.getSoPTH(maHoaDon));
//        int tongSoPhieuTraHang = 0;
//        //
//        List<ChiTietHoaDon> listCTHD;
//
//        if (coPTH) {
//            listCTHD = ChiTietHoaDonDAO.getChiTietHoaDonDaTruPTHTheoMaHD(hoaDon);
//            tongSoPhieuTraHang = HoaDonDAO.getSoPTH(maHoaDon);
//        } else {
//            listCTHD = ChiTietHoaDonDAO.getChiTietHoaDonTheoMaHD(hoaDon);
//        }
//
//        long ngayLap = ChronoUnit.DAYS.between(LocalDate.now(), hoaDon.getNgayLapHoaDon()) * -1;
//        if (ngayLap <= 30) {
//            System.out.println(ngayLap);
//            // Them du lieu vao bang cthd
//            lblSoLanTra.setText(tongSoPhieuTraHang+"");
//            lblSoNgayHD.setText(ngayLap+"");
//            lblTongTienTra.setText(dinhDangTien(HoaDonDAO.getTongTienCacPTH(maHoaDon)));
//            System.out.println("Sửa thành công");
//            themDuLieuCTHDVaoBang(listCTHD);
//            taoThongTinPhieu(maHoaDon);
//
//            if (hoaDon.getKhachHang() != null) {
//                String tenKhach = hoaDon.getKhachHang().getTen(); // Hoặc getHoTen() tùy Entity của bạn
//                txtTenKhachHang.setText(tenKhach);
//
//                // Kiểm tra nếu là khách lẻ (ví dụ mã KH-00000) thì không hiện điểm
//                if (!hoaDon.getKhachHang().getMaKH().equalsIgnoreCase("KH-00000")) {
//                    txtDiemTichLuy.setText(String.valueOf(hoaDon.getKhachHang().getDiemTichLuy()));
//                } else {
//                    txtDiemTichLuy.setText("0");
//                }
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "Hóa đơn đã lập hơn 30 ngày, theo nguyên tắc không thể trả hàng!");
//        }

    //   }



//    private void themDuLieuCTHDVaoBang(List<ChiTietHoaDon> listCTHD) {
//        int stt = 0;
//        DefaultTableModel bangCTHD = (DefaultTableModel) tblCTHD.getModel();
//        bangCTHD.setRowCount(0);
//        Object[] row = new Object[9];
//        for (ChiTietHoaDon cthd : listCTHD) {
//            stt++;
//            String maCTHD = cthd.getMaChiTietHoaDon();
//            String tenSanPham = cthd.getDonViTinh().getSanPham().getTen();
//            int soLuong = cthd.getSoLuong();
//            String donViTinh = cthd.getDonViTinh().getTenDonVi();
//            double donGia = cthd.getDonGia();
//            double giamGia = cthd.getGiamGia();
//            double thanhTien = cthd.getThanhTien() >= 0 ? cthd.getThanhTien() : 0;
//            boolean chon = Boolean.FALSE;
//            row[0] = stt;
//            row[1] = maCTHD;
//            row[2] = tenSanPham;
//            row[3] = soLuong < 0 ? 0 : soLuong;
//            row[4] = donViTinh;
//            row[5] = dinhDangTien(donGia);
//            row[6] = giamGia*100;
//            row[7] = dinhDangTien(thanhTien);
//            row[8] = chon;
//            if (soLuong <= 0) {
//                String traHet = "Đã trả hết ";
//                row[2] = traHet + tenSanPham;
//            }
//            bangCTHD.addRow(row);
//        }
//    }

    // Thêm dữ liệu vào "phiếu trả hàng"
//    private void themDongBangPhieuTraHang(String maCTHD) {
//        ChiTietHoaDon cthd = ChiTietHoaDonDAO.getChiTietHoaDonTheoMaCTHD(maCTHD);
//        DefaultTableModel dtm = (DefaultTableModel) tblTraHang.getModel();
//        Object[] rowData = new Object[11];
//
//        int stt = dtm.getRowCount() + 1;
//        String tenSanPham = cthd.getDonViTinh().getSanPham().getTen();
//        int soLuong = cthd.getSoLuong();
//        double donGia = cthd.getDonGia();
//        double giamGia = cthd.getGiamGia();
//        double thanhTien = soLuong * donGia - (soLuong * donGia*(giamGia/100));
//        String lyDoTra = TruongHopDoiTraEnum.HANG_LOI_DO_NHA_SAN_XUAT.getTruongHopDoiTra();
//        boolean sanPhamNguyenVen = Boolean.TRUE;
//        String giaTriHoanTra = null;
//        double thanhTienHoanTra = 0;
//
//        rowData[0] = stt;
//        rowData[1] = tenSanPham;
//        rowData[2] = soLuong;
//        rowData[3] = dinhDangTien(donGia);
//        rowData[4] = giamGia * 100;
//        rowData[5] = dinhDangTien(thanhTien);
//        rowData[6] = lyDoTra;
//        rowData[7] = sanPhamNguyenVen;
//        rowData[8] = giaTriHoanTra;
//        rowData[9] = dinhDangTien(thanhTienHoanTra);
//        rowData[10] = maCTHD;
//
//        dtm.addRow(rowData);
//
//        taoLyDo();
//
//    }

//    private void themDongBangPhieuTraHangDaTungTraRoi(String maCTHD) {
//        ChiTietHoaDon cthd = ChiTietHoaDonDAO.getChiTietHoaDonDaTungTraRoiTheoMaCTHD(maCTHD);
//        DefaultTableModel dtm = (DefaultTableModel) tblTraHang.getModel();
//        Object[] rowData = new Object[11];
//
//        int stt = dtm.getRowCount() + 1;
//        String tenSanPham = cthd.getDonViTinh().getSanPham().getTen();
//        int soLuong = cthd.getSoLuong();
//        double donGia = cthd.getDonGia();
//        double giamGia = cthd.getGiamGia();
//        double thanhTien = cthd.getThanhTien();
//        String lyDoTra = TruongHopDoiTraEnum.HANG_LOI_DO_NHA_SAN_XUAT.getTruongHopDoiTra();
//        boolean sanPhamNguyenVen = Boolean.TRUE;
//        String giaTriHoanTra = null;
//        double thanhTienHoanTra = 0;
//
//        rowData[0] = stt;
//        rowData[1] = tenSanPham;
//        rowData[2] = soLuong;
//        rowData[3] = dinhDangTien(donGia);
//        rowData[4] = giamGia*100;
//        rowData[5] = dinhDangTien(thanhTien);
//        rowData[6] = lyDoTra;
//        rowData[7] = sanPhamNguyenVen;
//        rowData[8] = giaTriHoanTra;
//        rowData[9] = dinhDangTien(thanhTienHoanTra);
//        rowData[10] = maCTHD;
//        dtm.addRow(rowData);
//        taoLyDo();
//    }

//    public double boDinhDangTien(String formatted) {
//        // Bước 1: Loại bỏ "VNĐ" và khoảng trắng
//        String cleaned = formatted.replace("VNĐ", "").trim();
//
//        // Bước 2: Loại bỏ dấu phẩy
//        cleaned = cleaned.replace(",", "");
//
//        // Bước 3: Chuyển thành double
//        return Double.parseDouble(cleaned);
//    }

//    private void taoThongTinPhieu(String maHoaDon) {
//        txtMaHoaDonTrongPhieuTraHang.setText(maHoaDon);
//        int ngay = LocalDate.now().getDayOfMonth();
//        int thang = LocalDate.now().getMonthValue();
//        int nam = LocalDate.now().getYear();
//        jTextField5.setText(ngay + "/" + thang + "/" + nam);
//
//        // GỌI BUS: Sinh mã phiếu
//        String maPhieuTraHang = TraHangBUS.phatSinhMaPhieuTraHang();
//        txtMaPhieuTraHang.setText(maPhieuTraHang);
//    }
//    private void taoLyDo() {
//        JComboBox<String> cbbLyDo = new JComboBox<>();
//        cbbLyDo.addItem(TruongHopDoiTraEnum.HANG_LOI_DO_NHA_SAN_XUAT.getTruongHopDoiTra());
//        cbbLyDo.addItem(TruongHopDoiTraEnum.DI_UNG_MAN_CAM.getTruongHopDoiTra());
//        cbbLyDo.addItem(TruongHopDoiTraEnum.NHU_CAU_KHACH_HANG.getTruongHopDoiTra());
//
//        TableColumn colLyDo = tblTraHang.getColumnModel().getColumn(6);
//        colLyDo.setCellEditor(new DefaultCellEditor(cbbLyDo));
//    }

//    private void capNhatTongThanhTien() {
//        DefaultTableModel dtm = (DefaultTableModel) tblTraHang.getModel();
//        double tongThanhTien = 0;
//        for (int i = 0; i < dtm.getRowCount(); i++) {
//            tongThanhTien = tongThanhTien + boDinhDangTien(dtm.getValueAt(i, 9).toString());
//        }
//        txtTongThanhTien.setText(dinhDangTien(tongThanhTien));
//        // Kiểm tra nếu là khách lẻ thì không trừ điểm
//        String diemHienTaiStr = txtDiemTichLuy.getText();
//        if (diemHienTaiStr != null && !diemHienTaiStr.isEmpty() && !diemHienTaiStr.equals("0")) {
//            // Giả sử quy đổi: 1.000 VNĐ hoàn tiền = Trừ 1 điểm tích lũy
//            // Bạn có thể sửa số 1000 thành hệ số quy đổi của cửa hàng bạn
//            int diemTru = (int) (tongThanhTien / 1000);
//
//            txtDiemTru.setText(String.valueOf(diemTru));
//        } else {
//            txtDiemTru.setText("0");
//        }
//    }

//    private String phatSinhMaPhieuTraHang() {
//        int ngay = LocalDate.now().getDayOfMonth();
//        int thang = LocalDate.now().getMonthValue();
//        int nam = LocalDate.now().getYear();
//        nam = nam % 1000;
//        String ngayThangNam = String.format("%02d%02d%02d", ngay, thang, nam);
//        int soPhieuHomNay = PhieuTraHangDAO.phieuTraHangMoiNhatHomNay();
//        String maPhieuTraHang = String.format("PTH-%s-%04d", ngayThangNam, soPhieuHomNay + 1);
//
//        return maPhieuTraHang;
//    }

//    private List<ChiTietPhieuTraHang> getListCTPTH(PhieuTraHang pth) {
//
//        DefaultTableModel dtm = (DefaultTableModel) tblTraHang.getModel();
//        List<ChiTietPhieuTraHang> listPTH = new ArrayList<>();
//
//        if (dtm.getColumnCount() == 0) {
//            throw new IllegalArgumentException("Không có CTPTH");
//        } else {
//            for (int i = 0; i < dtm.getRowCount(); i++) {
//
//                String maCTHD = dtm.getValueAt(i, 10).toString();
//
//                ChiTietHoaDon cthd = ChiTietHoaDonDAO.getChiTietHoaDonTheoMaCTHD(maCTHD);
//                TruongHopDoiTraEnum truongHopDoiTra = TruongHopDoiTraEnum.HANG_LOI_DO_NHA_SAN_XUAT;
//                if (dtm.getValueAt(i, 6).toString()
//                        .equals(TruongHopDoiTraEnum.HANG_LOI_DO_NHA_SAN_XUAT.getTruongHopDoiTra())) {
//                    truongHopDoiTra = TruongHopDoiTraEnum.HANG_LOI_DO_NHA_SAN_XUAT;
//                } else if (dtm.getValueAt(i, 6).toString()
//                        .equals(TruongHopDoiTraEnum.DI_UNG_MAN_CAM.getTruongHopDoiTra())) {
//                    truongHopDoiTra = TruongHopDoiTraEnum.DI_UNG_MAN_CAM;
//                } else if (dtm.getValueAt(i, 6).toString()
//                        .equals(TruongHopDoiTraEnum.NHU_CAU_KHACH_HANG.getTruongHopDoiTra())) {
//                    truongHopDoiTra = TruongHopDoiTraEnum.NHU_CAU_KHACH_HANG;
//                }
//                TinhTrangSanPhamEnum tinhTrang = TinhTrangSanPhamEnum.HANG_NGUYEN_VEN;
//                if (dtm.getValueAt(i, 7) == Boolean.FALSE) {
//                    tinhTrang = TinhTrangSanPhamEnum.HANG_KHONG_NGUYEN_VEN;
//                }
//
//                int soLuong = Integer.parseInt(dtm.getValueAt(i, 2).toString());
//                String giaTriHoanTra = dtm.getValueAt(i, 8).toString();
//
//                double thanhTienHoanTra = boDinhDangTien(dtm.getValueAt(i, 9).toString());
//
//                ChiTietPhieuTraHang ctpth = new ChiTietPhieuTraHang();
//                ctpth.setChiTietHoaDon(cthd);
//                ctpth.setPhieuTraHang(pth);
//                ctpth.setTruongHopDoiTra(truongHopDoiTra);
//                ctpth.setTinhTrangSanPham(tinhTrang);
//                ctpth.setTinhTrangSanPham(tinhTrang);
//                ctpth.setSoLuong(soLuong);
//                ctpth.setThanhTienHoanTra(thanhTienHoanTra);
//                ctpth.setGiaTriHoanTra(giaTriHoanTra);
//                listPTH.add(ctpth);
//            }
//        }
//        return listPTH;
//    }

//    private PhieuTraHang getPhieuTraHang() {
//        PhieuTraHang pth = new PhieuTraHang();
//        String maPTH = txtMaPhieuTraHang.getText();
//        String maNV = null;
//        try {
//            maNV = NhanVienDAO.getNhanVienTheoMaNV(GiaoDienChinhGUI.getTk().getTenDangNhap()).getMaNV();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//
//        String maHD = txtMaHoaDonTrongPhieuTraHang.getText();
//        LocalDateTime ngayLap = LocalDateTime.now();
//        double tongTienHoanTra = boDinhDangTien(txtTongThanhTien.getText());
//
//        NhanVien nv = NhanVienDAO.timNVTheoMa(maNV);
//        HoaDon hd = HoaDonDAO.getHoaDonTheoMaHD(maHD);
//
//        pth.setMaPhieuTraHang(maPTH);
//        pth.setNhanVien(nv);
//        pth.setHoaDon(hd);
//        pth.setNgayLapPhieuTraHang(ngayLap);
//        pth.setTongTienHoanTra(tongTienHoanTra);
//
//        return pth;
//
//    }
//
//    private void taoPhieuTraHang(PhieuTraHang pth, List<ChiTietPhieuTraHang> list) {
//        int WIDTH = 171;
//        String LINE = "=".repeat(WIDTH);
//        String SEPARATOR = "-".repeat(WIDTH);
//        StringBuilder sb = new StringBuilder();
//        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
//        DecimalFormat df = new DecimalFormat("#,###");
//
//        // ===== Header =====
//        sb.append(LINE).append("\n");
//        sb.append(center("PHIẾU TRẢ HÀNG", WIDTH)).append("\n");
//        sb.append(LINE).append("\n");
//        sb.append(String.format("Mã phiếu trả hàng : %s\n", pth.getMaPhieuTraHang()));
//        sb.append(String.format("Mã hóa đơn        : %s\n", pth.getHoaDon().getMaHoaDon()));
//        sb.append(String.format("Nhân viên lập     : %s\n", pth.getNhanVien().getTen()));
//        sb.append(String.format("Ngày lập phiếu    : %s\n", pth.getNgayLapPhieuTraHang().format(fmt)));
//        sb.append("\n").append(SEPARATOR).append("\n");
//
//        // ===== Tiêu đề bảng =====
//        sb.append(String.format(
//            "%-4s %-45s %-5s %-10s %-10s %-12s %-15s %-15s %-25s %-15s %-15s\n",
//            "STT", "Sản phẩm", "SL", "ĐVT", "Đơn giá", "Giảm giá", "Thành tiền",
//            "Tình trạng", "Lý do trả", "% Hoàn trả", "Tiền trả"
//        ));
//        sb.append(SEPARATOR).append("\n");
//
//        // ===== Dòng chi tiết =====
//        int stt = 1;
//        double tongTienTra = 0;
//        for (ChiTietPhieuTraHang ct : list) {
//            String tenSP = ct.getChiTietHoaDon().getDonViTinh().getSanPham().getTen();
//            if (tenSP.length() > 45) tenSP = tenSP.substring(0, 45);
//
//            String donViTinh = ct.getChiTietHoaDon().getDonViTinh().getTenDonVi();
//            String tinhTrangSP = (ct.getTinhTrangSanPham() == TinhTrangSanPhamEnum.HANG_NGUYEN_VEN)
//                    ? "Nguyên vẹn" : "Đã sử dụng";
//
//            String lyDo = ct.getTruongHopDoiTra().getTruongHopDoiTra();
//            if (lyDo.length() > 25) lyDo = lyDo.substring(0, 25);
//
//            String phanTramHoanTra = ct.getGiaTriHoanTra();
//            double thanhTienTra = ct.getThanhTienHoanTra();
//            tongTienTra += thanhTienTra;
//
//            sb.append(String.format(
//                "%-4d %-45s %-5d %-10s %-10s %-12s %-15s %-15s %-25s %-15s %-15s\n",
//                stt++, tenSP, ct.getSoLuong(), donViTinh,
//                df.format(ct.getChiTietHoaDon().getDonGia()),
//                df.format(ct.getChiTietHoaDon().getGiamGia()),
//                df.format(ct.getSoLuong() * ct.getChiTietHoaDon().getDonGia() - ct.getChiTietHoaDon().getGiamGia()),
//                tinhTrangSP, lyDo, phanTramHoanTra, df.format(thanhTienTra)
//            ));
//        }
//
//        sb.append(SEPARATOR).append("\n");
//
//        // ===== Footer =====
//        String tongCongStr = "TỔNG TIỀN HOÀN TRẢ: " + df.format(tongTienTra) + " VND";
//        sb.append(alignRight(tongCongStr, WIDTH)).append("\n");
//        sb.append(LINE).append("\n");
//        sb.append(center("CẢM ƠN QUÝ KHÁCH, HẸN GẶP LẠI!", WIDTH)).append("\n");
//        sb.append(LINE).append("\n");
//
//        // ===== Hiển thị trong JDialog =====
//        JDialog dialog = new JDialog((Frame) null, "Phiếu trả hàng " + pth.getMaPhieuTraHang(), true);
//        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
//        dialog.setSize(1220, 600);
//        dialog.setLocationRelativeTo(null);
//        dialog.setResizable(true);
//
//        // Nội dung hiển thị
//        JTextArea textArea = new JTextArea(sb.toString());
//        textArea.setEditable(false);
//        textArea.setFont(new Font("Monospaced", Font.PLAIN, 11)); // Font nhỏ gọn
//        textArea.setCaretPosition(0); // Cuộn lên đầu khi mở
//
//        // Cuộn cả dọc và ngang
//        JScrollPane scrollPane = new JScrollPane(textArea);
//        scrollPane.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
//        scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
//        scrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
//
//
//        dialog.setLayout(new BorderLayout(10, 10));
//        dialog.add(scrollPane, BorderLayout.CENTER);
//        dialog.setVisible(true);
//    }


    private static String center(String text, int width) {
        int padSize = (width - text.length()) / 2;
        return " ".repeat(Math.max(0, padSize)) + text;
    }

    private static String alignRight(String text, int width) {
        int padding = width - text.length();
        if (padding < 0) padding = 0;
        return " ".repeat(padding) + text;
    }


//    private void luuPhieuVaoCSDL(PhieuTraHang pth, List<ChiTietPhieuTraHang> list) {
//        PhieuTraHangDAO.themPhieuTra(pth);
//        for (ChiTietPhieuTraHang ctpth : list) {
//            ChiTietPhieuTraDAO.insertChiTietPhieuTra(ctpth);
//        }
//    }


//    private void capNhatTongTienTra() {
//    DefaultTableModel dtm = (DefaultTableModel) tblTraHang.getModel();
//
//    for (int i = 0; i < tblTraHang.getRowCount(); i++) {
//        // 1. Lấy dữ liệu từ bảng
//        int soLuong = Integer.parseInt(dtm.getValueAt(i, 2).toString());
//        String maCTHD = dtm.getValueAt(i, 10).toString();
//
//        // Validation: Kiểm tra số lượng hợp lệ (Logic này giữ ở GUI hoặc chuyển vào BUS tùy bạn, tạm thời giữ nguyên)
//        if (soLuong > ChiTietHoaDonDAO.getChiTietHoaDonDaTungTraRoiTheoMaCTHD(maCTHD).getSoLuong()) {
//            dtm.setValueAt(1,i, 2);
//            JOptionPane.showMessageDialog(null, "Số lượng trả không được vượt quá số lượng mua là "+ChiTietHoaDonDAO.getChiTietHoaDonDaTungTraRoiTheoMaCTHD(maCTHD).getSoLuong()+"! (Dòng " + (i + 1) + ")");
//            // Reset lại số lượng về mặc định hoặc xử lý tùy ý
//            return;
//        }
//        else if(soLuong<=0){
//            dtm.setValueAt(1,i, 2);
//            JOptionPane.showMessageDialog(null, "Số lượng trả không được bé hơn 1 tại (Dòng " + (i + 1) + ")");
//            // Reset lại số lượng về mặc định hoặc xử lý tùy ý
//            return;
//        }
//
//        // 2. GỌI BUS: Tính thành tiền gốc (Cột 5)
//        double donGia = boDinhDangTien(dtm.getValueAt(i, 3).toString());
//        double khuyenMai = Double.parseDouble(dtm.getValueAt(i, 4).toString());
//
//        double thanhTienGoc = TraHangBUS.tinhThanhTienGoc(soLuong, donGia, khuyenMai);
//        dtm.setValueAt(dinhDangTien(thanhTienGoc), i, 5);
//
//        // 3. Chuẩn bị dữ liệu để tính hoàn trả
//        boolean isNguyenVen = (boolean) dtm.getValueAt(i, 7);
//        String lyDoString = dtm.getValueAt(i, 6).toString();
//        TruongHopDoiTraEnum lyDoEnum = convertStringToEnum(lyDoString); // Hàm phụ trợ chuyển đổi (xem bên dưới)
//
//        // 4. GỌI BUS: Lấy phần trăm hiển thị (Cột 8)
//        String hienThiPhanTram = TraHangBUS.layPhanTramHoanTra(lyDoEnum, isNguyenVen);
//        dtm.setValueAt(hienThiPhanTram, i, 8);
//
//        // 5. GỌI BUS: Tính tiền hoàn trả (Cột 9)
//        double tienHoanTra = TraHangBUS.tinhTienHoanTraItem(thanhTienGoc, lyDoEnum, isNguyenVen);
//        dtm.setValueAt(dinhDangTien(tienHoanTra), i, 9);
//    }
//
//    // Cập nhật tổng tiền cuối cùng
//    capNhatTongThanhTien();
//}

    // Hàm phụ trợ để code gọn hơn (bạn thêm vào dưới cùng class GUI)
//    private TruongHopDoiTraEnum convertStringToEnum(String lyDo) {
//        if (lyDo.equals(TruongHopDoiTraEnum.HANG_LOI_DO_NHA_SAN_XUAT.getTruongHopDoiTra()))
//            return TruongHopDoiTraEnum.HANG_LOI_DO_NHA_SAN_XUAT;
//        if (lyDo.equals(TruongHopDoiTraEnum.DI_UNG_MAN_CAM.getTruongHopDoiTra()))
//            return TruongHopDoiTraEnum.DI_UNG_MAN_CAM;
//        return TruongHopDoiTraEnum.NHU_CAU_KHACH_HANG;
//    }

    // ============================================================
    // HELPER METHODS - client-server pattern
    // ============================================================

    /**
     * Tìm hóa đơn để trả hàng – dùng nhiều request riêng thay vì một DTO tổng hợp.
     *
     * Các command dùng:
     *  - GET_HOA_DON_BY_MA       → HoaDonDTO
     *  - GET_SO_PTH              → int   (số phiếu trả đã tạo cho HD này)
     *  - GET_TONG_TIEN_CAC_PTH   → double
     *  - GET_SO_PTH_CUOI         → String (mã PTH mới sinh)
     *  - GET_KHACH_HANG_BY_MA    → KhachHangDTO  (chỉ gọi nếu HD có maKH)
     *  - GET_CTHD_BY_MA_HD       → ArrayList<ChiTietHoaDonDTO>
     */
    private void timHoaDonDeTraHang() {
        String maHoaDon = txtNhapMaHoaDon.getText().trim();
        if (maHoaDon.isEmpty() || maHoaDon.equals("[F3]")) return;
        resetInfoPanels();

        // ── 1. Lấy hóa đơn ──────────────────────────────────────
        Response resHD = SocketClient.getInstance().sendRequest(
                new Request(CommandType.GET_HOA_DON_BY_MA, maHoaDon));
        if (!resHD.isSuccess()) {
            JOptionPane.showMessageDialog(null, resHD.getMessage());
            return;
        }
        HoaDonDTO hd = (HoaDonDTO) resHD.getData();

        // Chặn HD quá 30 ngày
        long soNgay = ChronoUnit.DAYS.between(
                hd.getNgayLapHoaDon().toLocalDate(), LocalDate.now());
        if (soNgay > 30) {
            JOptionPane.showMessageDialog(null,
                    "Hóa đơn đã lập hơn 30 ngày, không thể trả hàng!");
            return;
        }

        // ── 2. Số phiếu trả hàng đã có của HD này ───────────────
        Response resSoPTH = SocketClient.getInstance().sendRequest(
                new Request(CommandType.GET_SO_PTH, maHoaDon));
        int soPTH = (resSoPTH.isSuccess() && resSoPTH.getData() != null)
                ? ((Number) resSoPTH.getData()).intValue() : 0;

        // ── 3. Tổng tiền các phiếu trả ──────────────────────────
        Response resTong = SocketClient.getInstance().sendRequest(
                new Request(CommandType.GET_TONG_TIEN_CAC_PTH, maHoaDon));
        double tongTienPTH = (resTong.isSuccess() && resTong.getData() != null)
                ? ((Number) resTong.getData()).doubleValue() : 0;

        // ── 4. Sinh mã phiếu trả hàng mới ───────────────────────
        Response resSoCuoi = SocketClient.getInstance().sendRequest(
                new Request(CommandType.GET_SO_PTH_CUOI, null));
        int soCuoi = (resSoCuoi.isSuccess() && resSoCuoi.getData() != null)
                ? ((Number) resSoCuoi.getData()).intValue() : 0;
        String maPTHMoi = phatSinhMaPhieuTraHang(soCuoi + 1);

        // ── 5. Thông tin khách hàng (nếu có) ────────────────────
        String tenKH = "Khách lẻ";
        int diem = 0;
        if (hd.getMaKH() != null && !hd.getMaKH().isBlank()) {
            Response resKH = SocketClient.getInstance().sendRequest(
                    new Request(CommandType.GET_KHACH_HANG_BY_MA, hd.getMaKH()));
            if (resKH.isSuccess() && resKH.getData() instanceof KhachHangDTO kh) {
                tenKH = kh.getHoTenDem() + " " + kh.getTen();
                diem  = kh.getDiemTichLuy();
            }
        }

        // ── 6. Chi tiết hóa đơn → điền tblCTHD ─────────────────
        Response resCTHD = SocketClient.getInstance().sendRequest(
                new Request(CommandType.GET_CTHD_BY_MA_HD, maHoaDon));
        if (!resCTHD.isSuccess()) {
            JOptionPane.showMessageDialog(null, resCTHD.getMessage());
            return;
        }

        // ── Cập nhật 3 card thông tin ────────────────────────────
        lblSoLanTra.setText(String.valueOf(soPTH));
        lblSoNgayHD.setText(String.valueOf(soNgay));
        lblTongTienTra.setText(dinhDangTien(tongTienPTH));

        txtTenKhachHang.setText(tenKH);
        txtDiemTichLuy.setText(String.valueOf(diem));

        txtMaHoaDonTrongPhieuTraHang.setText(maHoaDon);
        jTextField5.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        txtMaPhieuTraHang.setText(maPTHMoi);

        // ── 6.5. Tính số lượng đã trả của từng CTHD trong các phiếu trả trước ──
        java.util.Map<String, Integer> daTraMap = tinhSoLuongDaTra(maHoaDon);

        // ── Điền bảng chi tiết hóa đơn ──────────────────────────
        // tblCTHD columns: STT | Mã CTHD | Tên SP | Số lượng | ĐVT | Đơn giá | Giảm giá | Thành tiền | Chọn
        DefaultTableModel bangCTHD = (DefaultTableModel) tblCTHD.getModel();
        bangCTHD.setRowCount(0);
        @SuppressWarnings("unchecked")
        ArrayList<ChiTietHoaDonDTO> dsCTHD = (ArrayList<ChiTietHoaDonDTO>) resCTHD.getData();
        int stt = 1;
        for (ChiTietHoaDonDTO ct : dsCTHD) {
            int daTra  = daTraMap.getOrDefault(ct.getMaChiTietHoaDon(), 0);
            int conLai = ct.getSoLuong() - daTra;
            if (conLai <= 0) continue;   // bỏ qua sản phẩm đã trả hết

            // Thành tiền hiển thị tính lại theo số lượng còn có thể trả
            double thanhTienConLai = ct.getDonGia() * conLai * (1 - ct.getGiamGia() / 100.0);

            bangCTHD.addRow(new Object[]{
                    stt++,
                    ct.getMaChiTietHoaDon(),
                    "ct.getTenSanPham()",
                    conLai,                              // số lượng còn được phép trả
                    "ct.getTenDonViTinh()",
                    dinhDangTien(ct.getDonGia()),
                    ct.getGiamGia(),
                    dinhDangTien(thanhTienConLai),
                    Boolean.FALSE                        // cột Chọn
            });
        }
        txtNhapMaHoaDon.setText("");
    }

    /**
     * Gom số lượng đã trả của từng CTHD trong tất cả các phiếu trả trước đó.
     * Key = maChiTietHoaDon, Value = tổng số lượng đã trả.
     */
    private java.util.Map<String, Integer> tinhSoLuongDaTra(String maHD) {
        java.util.Map<String, Integer> result = new java.util.HashMap<>();

        // 1. Lấy danh sách phiếu trả của HD này
        Response resPTH = SocketClient.getInstance().sendRequest(
                new Request(CommandType.GET_PTH_BY_MA_HD, maHD));
        if (!resPTH.isSuccess() || !(resPTH.getData() instanceof ArrayList)) return result;
        @SuppressWarnings("unchecked")
        ArrayList<PhieuTraHangDTO> dsPTH = (ArrayList<PhieuTraHangDTO>) resPTH.getData();

        // 2. Với mỗi phiếu, lấy chi tiết và cộng dồn số lượng
        for (PhieuTraHangDTO pth : dsPTH) {
            Response resCT = SocketClient.getInstance().sendRequest(
                    new Request(CommandType.GET_CTPTH_BY_MA_PTH, pth.getMaPhieuTraHang()));
            if (!resCT.isSuccess() || !(resCT.getData() instanceof ArrayList)) continue;

            @SuppressWarnings("unchecked")
            ArrayList<ChiTietPhieuTraHangDTO> dsCT =
                    (ArrayList<ChiTietPhieuTraHangDTO>) resCT.getData();
            for (ChiTietPhieuTraHangDTO ct : dsCT) {
                result.merge(ct.getMaChiTietHoaDon(), ct.getSoLuong(), Integer::sum);
            }
        }
        return result;
    }

    /**
     * Tao combo lý do trả hàng cho cột 6 của tblTraHang.
     */
    private void taoLyDo() {
        JComboBox<String> cbbLyDo = new JComboBox<>();
        cbbLyDo.addItem("Hàng lỗi do nhà sản xuất");
        cbbLyDo.addItem("Dị ứng/mẫn cảm");
        cbbLyDo.addItem("Nhu cầu khách hàng");
        TableColumn colLyDo = tblTraHang.getColumnModel().getColumn(6);
        colLyDo.setCellEditor(new DefaultCellEditor(cbbLyDo));
    }

    /**
     * Cập nhật tổng thành tiền hoàn trả và điểm trừ.
     */
    private void capNhatTongThanhTien() {
        DefaultTableModel dtm = (DefaultTableModel) tblTraHang.getModel();
        double tongThanhTien = 0;
        for (int i = 0; i < dtm.getRowCount(); i++) {
            tongThanhTien += boDinhDangTien(dtm.getValueAt(i, 9).toString());
        }
        txtTongThanhTien.setText(dinhDangTien(tongThanhTien));

        String diemStr = txtDiemTichLuy.getText();
        if (diemStr != null && !diemStr.isEmpty() && !diemStr.equals("0")) {
            txtDiemTru.setText(String.valueOf((int) (tongThanhTien / 1000)));
        } else {
            txtDiemTru.setText("0");
        }
    }

    /**
     * Hiển thị phiếu trả hàng dạng text trong JDialog.
     */
    private void hienThiPhieuTraHang(String noiDung, String maPTH) {
        JDialog dialog = new JDialog((Frame) null, "Phiếu trả hàng " + maPTH, true);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        dialog.setSize(1220, 600);
        dialog.setLocationRelativeTo(null);
        dialog.setResizable(true);

        JTextArea textArea = new JTextArea(noiDung);
        textArea.setEditable(false);
        textArea.setFont(new Font("Monospaced", Font.PLAIN, 11));
        textArea.setCaretPosition(0);

        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);

        dialog.setLayout(new BorderLayout(10, 10));
        dialog.add(scrollPane, BorderLayout.CENTER);
        dialog.setVisible(true);
    }



    /**
     * Tạo một card thông tin với tiêu đề + giá trị
     */
    private javax.swing.JPanel createInfoCard(String title, javax.swing.JLabel valueLabel,
                                              java.awt.Color bgColor, java.awt.Color titleColor) {
        javax.swing.JPanel card = new javax.swing.JPanel(new java.awt.BorderLayout());
        card.setBackground(bgColor);
        card.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(titleColor, 2, true),
                javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));

        // Tiêu đề
        javax.swing.JLabel lblTitle = new javax.swing.JLabel(title);
        lblTitle.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        lblTitle.setForeground(titleColor);
        card.add(lblTitle, java.awt.BorderLayout.NORTH);

        // Giá trị
        valueLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 28));
        valueLabel.setForeground(titleColor);
        valueLabel.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        card.add(valueLabel, java.awt.BorderLayout.CENTER);

        return card;
    }

    // =========================================================
    //  CÁC METHOD CÒN THIẾU – thêm vào để hoàn chỉnh file
    // =========================================================

    /**
     * Khởi tạo 3 card thông tin (số lần trả / số ngày / tổng tiền đã trả).
     * jPanel13 layout ban đầu là GridLayout(1,2), đổi sang GridLayout(1,3) để chứa 3 card.
     */
    private void initInfoPanels() {
        lblSoLanTra    = new javax.swing.JLabel("0");
        lblSoNgayHD    = new javax.swing.JLabel("0");
        lblTongTienTra = new javax.swing.JLabel("0 VNĐ");

        javax.swing.JPanel cardLanTra = createInfoCard(
                "Số lần trả", lblSoLanTra,
                new java.awt.Color(255, 243, 224), new java.awt.Color(239, 108, 0));
        javax.swing.JPanel cardNgay = createInfoCard(
                "Số ngày kể từ lập HD", lblSoNgayHD,
                new java.awt.Color(227, 242, 253), new java.awt.Color(30, 136, 229));
        javax.swing.JPanel cardTongTien = createInfoCard(
                "Tổng tiền đã trả", lblTongTienTra,
                new java.awt.Color(232, 245, 233), new java.awt.Color(56, 142, 60));

        jPanel13.setLayout(new java.awt.GridLayout(1, 3, 10, 0));
        jPanel13.add(cardLanTra);
        jPanel13.add(cardNgay);
        jPanel13.add(cardTongTien);
    }

    /** Reset 3 card về giá trị mặc định. */
    private void resetInfoPanels() {
        if (lblSoLanTra    != null) lblSoLanTra.setText("0");
        if (lblSoNgayHD    != null) lblSoNgayHD.setText("0");
        if (lblTongTienTra != null) lblTongTienTra.setText("0 VNĐ");
    }

    /** Xóa toàn bộ form sau khi tạo phiếu trả thành công. */
    private void xoaRongTatCa() {
        ((javax.swing.table.DefaultTableModel) tblCTHD.getModel()).setRowCount(0);
        ((javax.swing.table.DefaultTableModel) tblTraHang.getModel()).setRowCount(0);

        txtNhapMaHoaDon.setText("");
        txtTenKhachHang.setText("");
        txtDiemTichLuy.setText("0");
        txtDiemTru.setText("0");
        txtTongThanhTien.setText("");
        txtMaPhieuTraHang.setText("");
        txtMaHoaDonTrongPhieuTraHang.setText("");
        jTextField3.setText("");
        jTextField5.setText("");
        jLabel6.setText("Số lượng đã chọn: 0");
        resetInfoPanels();
    }

    private String dinhDangTien(double tien) {
        return new java.text.DecimalFormat("#,###").format(tien) + " VNĐ";
    }

    public double boDinhDangTien(String formatted) {
        String cleaned = formatted.replace("VNĐ", "").replace(",", "").trim();
        if (cleaned.isEmpty()) return 0;
        return Double.parseDouble(cleaned);
    }

    /** Sinh mã phiếu trả hàng theo format PTH-DDMMYY-XXXX */
    private String phatSinhMaPhieuTraHang(int soThuTu) {
        java.time.LocalDate t = java.time.LocalDate.now();
        String ddMMyy = String.format("%02d%02d%02d",
                t.getDayOfMonth(), t.getMonthValue(), t.getYear() % 100);
        return String.format("PTH-%s-%04d", ddMMyy, soThuTu);
    }

    /**
     * Map text lý do trên UI sang tên enum TruongHopDoiTraEnum của server.
     * TODO: kiểm tra tên enum thực tế bên server.entity.TruongHopDoiTraEnum
     */
    private String mapLyDoSangEnum(String lyDo) {
        return switch (lyDo) {
            case "Hàng lỗi do nhà sản xuất" -> "HANG_LOI_DO_NHA_SAN_XUAT";   // ← l viết thường (theo enum server)
            case "Dị ứng/mẫn cảm"          -> "DI_UNG_MAN_CAM";
            case "Nhu cầu khách hàng"      -> "NHU_CAU_KHACH_HANG";
            default                         -> "NHU_CAU_KHACH_HANG";
        };
    }

    // ── Phím tắt ─────────────────────────────────────────────

    private void mapKeyToFocus(String key, javax.swing.JComponent component) {
        javax.swing.InputMap  im = component.getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        javax.swing.ActionMap am = component.getActionMap();
        im.put(javax.swing.KeyStroke.getKeyStroke(key), "focus_" + key);
        am.put("focus_" + key, new javax.swing.AbstractAction() {
            @Override public void actionPerformed(java.awt.event.ActionEvent e) {
                component.requestFocus();
                if (component instanceof javax.swing.JTextField tf) tf.selectAll();
            }
        });
    }

    private void mapKeyToClickButton(String key, javax.swing.AbstractButton button) {
        javax.swing.InputMap  im = button.getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        javax.swing.ActionMap am = button.getActionMap();
        im.put(javax.swing.KeyStroke.getKeyStroke(key), "click_" + key);
        am.put("click_" + key, new javax.swing.AbstractAction() {
            @Override public void actionPerformed(java.awt.event.ActionEvent e) { button.doClick(); }
        });
    }
}